server:
  port: 31000
spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      database: xc_cms
      host: 39.107.236.181
      port: 27017
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
xuecheng:
  mq:
    # cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
    queue: ${QUEUE:queue_cms_postpage_01}
    # 此routingKey为门户站点ID
    routingKey: ${ROUTING_KEY:5a751fab6abb5044e0d19ea1}
